strip spaces for templates select and searchable select
mpcmf/mpcmf-core pull request #18
Opened 2020-02-28 08:19 UTC by alexbilevskiy

2020-02-28 13:17 UTC, gilberg-vrn approved these changes

2020-08-07 10:42 UTC, greevex requested changes

2020-08-07 10:42 UTC, greevex commented on src/system/modules/moduleBase/templates/forms/generate/type_searchebleselect.tpl
> +                {assign var="selected" value=($fieldValue == $itemValue)}
Это не похоже на изменение только по strip-ам

2020-08-07 10:42 UTC, greevex commented on src/system/modules/moduleBase/templates/forms/generate/type_searchebleselect.tpl
> +        {assign var="fieldValue" value=[]}
И это не похоже на изменение только по strip-ам

2020-08-07 10:45 UTC, gilberg-vrn commented on src/system/modules/moduleBase/templates/forms/generate/type_searchebleselect.tpl
> +                {assign var="selected" value=($fieldValue == $itemValue)}
Кажись, это особенность диффа:
![image](https://user-images.githubusercontent.com/11310253/89638243-271ac480-d8b4-11ea-9971-af281c9a9274.png)
Там же выравнивание на один уровень ушло по всему файлу - вот он и не знает, что с чем клеить...

2020-08-07 10:47 UTC, greevex approved these changes

2020-08-07 11:42 UTC, merged